version: '3.8'

services:
  # Laravel API Backend
  backend:
    build:
      context: ./laravel-api
      dockerfile: Dockerfile
    container_name: quicksale-backend
    restart: unless-stopped
    volumes:
      - ./laravel-api:/var/www/html
      - ./laravel-api/vendor:/var/www/html/vendor
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=quicksale
      - DB_USERNAME=quicksale
      - DB_PASSWORD=quicksale_password

  # Vue.js Frontend
  frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
    container_name: quicksale-frontend
    restart: unless-stopped
    volumes:
      - ./vue-frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: quicksale-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: quicksale
      MYSQL_USER: quicksale
      MYSQL_PASSWORD: quicksale_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quicksale-phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  mysql_data: